// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for the
/// [GetWorkflow][google.cloud.workflows.v1.Workflows.GetWorkflow] method.
///
/// [google.cloud.workflows.v1.Workflows.GetWorkflow]: <doc:Workflows/getWorkflow(request:)>
public struct GetWorkflowRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Name of the workflow for which information should be retrieved.
  /// Format: projects/{project}/locations/{location}/workflows/{workflow}
  public var name: Swift.String

  /// Optional. The revision of the workflow to retrieve. If the revision_id is
  /// empty, the latest revision is retrieved.
  /// The format is "000001-a4d", where the first six characters define
  /// the zero-padded decimal revision number. They are followed by a hyphen and
  /// three hexadecimal characters.
  public var revisionId: Swift.String

  /// Initialize a new instance of `GetWorkflowRequest`.
  public init(
    name: Swift.String = Swift.String(),
    revisionId: Swift.String = Swift.String(),
  ) {
    self.name = name
    self.revisionId = revisionId
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.workflows.v1.GetWorkflowRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
