// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for the
/// [ListWorkflows][google.cloud.workflows.v1.Workflows.ListWorkflows]
/// method.
///
/// [google.cloud.workflows.v1.Workflows.ListWorkflows]: <doc:Workflows/listWorkflows(request:)>
public struct ListWorkflowsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Project and location from which the workflows should be listed.
  /// Format: projects/{project}/locations/{location}
  public var parent: Swift.String

  /// Maximum number of workflows to return per call. The service might return
  /// fewer than this value even if not at the end of the collection. If a value
  /// is not specified, a default value of 500 is used. The maximum permitted
  /// value is 1000 and values greater than 1000 are coerced down to 1000.
  public var pageSize: Swift.Int32

  /// A page token, received from a previous `ListWorkflows` call.
  /// Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters provided to `ListWorkflows` must
  /// match the call that provided the page token.
  public var pageToken: Swift.String

  /// Filter to restrict results to specific workflows.
  /// For details, see <a href="https://google.aip.dev/160"
  /// class="external">AIP-160</a>.
  ///
  /// For example, if you are using the Google APIs Explorer:
  ///
  /// `state="SUCCEEDED"`
  ///
  /// or
  ///
  /// `createTime>"2023-08-01" AND state="FAILED"`
  public var filter: Swift.String

  /// Comma-separated list of fields that specify the order of the results.
  /// Default sorting order for a field is ascending. To specify descending order
  /// for a field, append a "desc" suffix.
  /// If not specified, the results are returned in an unspecified order.
  public var orderBy: Swift.String

  /// Initialize a new instance of `ListWorkflowsRequest`.
  public init(
    parent: Swift.String = Swift.String(),
    pageSize: Swift.Int32 = Swift.Int32(),
    pageToken: Swift.String = Swift.String(),
    filter: Swift.String = Swift.String(),
    orderBy: Swift.String = Swift.String(),
  ) {
    self.parent = parent
    self.pageSize = pageSize
    self.pageToken = pageToken
    self.filter = filter
    self.orderBy = orderBy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.workflows.v1.ListWorkflowsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
