// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for the
/// [ListWorkflowRevisions][google.cloud.workflows.v1.Workflows.ListWorkflowRevisions]
/// method.
///
/// [google.cloud.workflows.v1.Workflows.ListWorkflowRevisions]: <doc:Workflows/listWorkflowRevisions(request:)>
public struct ListWorkflowRevisionsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Workflow for which the revisions should be listed.
  /// Format: projects/{project}/locations/{location}/workflows/{workflow}
  public var name: Swift.String

  /// The maximum number of revisions to return per page. If a value is not
  /// specified, a default value of 20 is used. The maximum permitted value is
  /// 100. Values greater than 100 are coerced down to 100.
  public var pageSize: Swift.Int32

  /// The page token, received from a previous ListWorkflowRevisions call.
  /// Provide this to retrieve the subsequent page.
  public var pageToken: Swift.String

  /// Initialize a new instance of `ListWorkflowRevisionsRequest`.
  public init(
    name: Swift.String = Swift.String(),
    pageSize: Swift.Int32 = Swift.Int32(),
    pageToken: Swift.String = Swift.String(),
  ) {
    self.name = name
    self.pageSize = pageSize
    self.pageToken = pageToken
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.workflows.v1.ListWorkflowRevisionsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
