// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request for the
/// [ListWorkflowRevisions][google.cloud.workflows.v1.Workflows.ListWorkflowRevisions]
/// method.
///
/// [google.cloud.workflows.v1.Workflows.ListWorkflowRevisions]: <doc:WorkflowsClient/listWorkflowRevisions(request:options:)>
public struct ListWorkflowRevisionsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Workflow for which the revisions should be listed.
  /// Format: projects/{project}/locations/{location}/workflows/{workflow}
  public var name: Swift.String = Swift.String()

  /// The maximum number of revisions to return per page. If a value is not
  /// specified, a default value of 20 is used. The maximum permitted value is
  /// 100. Values greater than 100 are coerced down to 100.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The page token, received from a previous ListWorkflowRevisions call.
  /// Provide this to retrieve the subsequent page.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListWorkflowRevisionsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListWorkflowRevisionsRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.workflows.v1.ListWorkflowRevisionsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
