// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for the
/// [UpdateWorkflow][google.cloud.workflows.v1.Workflows.UpdateWorkflow]
/// method.
///
/// [google.cloud.workflows.v1.Workflows.UpdateWorkflow]: <doc:Workflows/updateWorkflow(request:)>
public struct UpdateWorkflowRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Workflow to be updated.
  public var workflow: Workflow?

  /// List of fields to be updated. If not present, the entire workflow
  /// will be updated.
  public var updateMask: GoogleCloudWkt.FieldMask?

  /// Initialize a new instance of `UpdateWorkflowRequest`.
  public init(
    workflow: Workflow? = nil,
    updateMask: GoogleCloudWkt.FieldMask? = nil,
  ) {
    self.workflow = workflow
    self.updateMask = updateMask
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.workflows.v1.UpdateWorkflowRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
