// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Workflows is used to deploy and execute workflow programs.
/// Workflows makes sure the program executes reliably, despite hardware and
/// networking interruptions.
///
/// @Snippet(path: "WorkflowsQuickstart")
public final class WorkflowsClient: Clients.WorkflowsProtocol, Sendable {
  let inner: any Clients.WorkflowsStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `WorkflowsClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.WorkflowsStub = try Clients.WorkflowsTransport(options)
    inner = Clients.WorkflowsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.WorkflowsLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists workflows in a given project and location.
  /// The default order is not specified.
  ///
  /// @Snippet(path: "Workflows_ListWorkflows")
  public func listWorkflows(
    request: ListWorkflowsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowsResponse {
    try await self.inner.listWorkflows(request: request, options: options)
  }

  /// Gets details of a single workflow.
  ///
  /// @Snippet(path: "Workflows_GetWorkflow")
  public func getWorkflow(
    request: GetWorkflowRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkflowsV1.Workflow {
    try await self.inner.getWorkflow(request: request, options: options)
  }

  /// Creates a new workflow. If a workflow with the specified name already
  /// exists in the specified project and location, the long running operation
  /// returns a [ALREADY_EXISTS][google.rpc.Code.ALREADY_EXISTS] error.
  ///
  /// @Snippet(path: "Workflows_CreateWorkflow")
  public func createWorkflow(
    request: CreateWorkflowRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createWorkflow(request: request, options: options)
  }

  /// Creates a new workflow. If a workflow with the specified name already
  /// exists in the specified project and location, the long running operation
  /// returns a [ALREADY_EXISTS][google.rpc.Code.ALREADY_EXISTS] error.
  ///
  /// @Snippet(path: "Workflows_CreateWorkflow")
  public func createWorkflowPollingUntilDone(
    request: CreateWorkflowRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Workflow> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Workflow>.State
      in
      return try op._extractStatus(Workflow.self)
    }
    let rawOp = try await self.createWorkflow(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Workflow>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a workflow with the specified name.
  /// This method also cancels and deletes all running executions of the
  /// workflow.
  ///
  /// @Snippet(path: "Workflows_DeleteWorkflow")
  public func deleteWorkflow(
    request: DeleteWorkflowRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteWorkflow(request: request, options: options)
  }

  /// Deletes a workflow with the specified name.
  /// This method also cancels and deletes all running executions of the
  /// workflow.
  ///
  /// @Snippet(path: "Workflows_DeleteWorkflow")
  public func deleteWorkflowPollingUntilDone(
    request: DeleteWorkflowRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteWorkflow(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates an existing workflow.
  /// Running this method has no impact on already running executions of the
  /// workflow. A new revision of the workflow might be created as a result of a
  /// successful update operation. In that case, the new revision is used
  /// in new workflow executions.
  ///
  /// @Snippet(path: "Workflows_UpdateWorkflow")
  public func updateWorkflow(
    request: UpdateWorkflowRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateWorkflow(request: request, options: options)
  }

  /// Updates an existing workflow.
  /// Running this method has no impact on already running executions of the
  /// workflow. A new revision of the workflow might be created as a result of a
  /// successful update operation. In that case, the new revision is used
  /// in new workflow executions.
  ///
  /// @Snippet(path: "Workflows_UpdateWorkflow")
  public func updateWorkflowPollingUntilDone(
    request: UpdateWorkflowRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Workflow> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Workflow>.State
      in
      return try op._extractStatus(Workflow.self)
    }
    let rawOp = try await self.updateWorkflow(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Workflow>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists revisions for a given workflow.
  ///
  /// @Snippet(path: "Workflows_ListWorkflowRevisions")
  public func listWorkflowRevisions(
    request: ListWorkflowRevisionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse {
    try await self.inner.listWorkflowRevisions(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Workflows_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "Workflows_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Workflows_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Workflows_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Workflows_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `WorkflowsClient`.
  ///
  /// To mock `WorkflowsClient` change your functions to receive
  /// `some WorkflowsProtocol` or `any WorkflowsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol WorkflowsProtocol: Sendable {
    /// See `WorkflowsClient.createWorkflow`.
    func createWorkflowPollingUntilDone(request: CreateWorkflowRequest) async throws
      -> any GoogleGax.PollableOperation<Workflow>

    /// See `WorkflowsClient.createWorkflow`.
    func createWorkflowPollingUntilDone(
      parent: Swift.String,
      workflow: Workflow?,
      workflowId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Workflow>

    /// See `WorkflowsClient.deleteWorkflow`.
    func deleteWorkflowPollingUntilDone(request: DeleteWorkflowRequest) async throws
      -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `WorkflowsClient.deleteWorkflow`.
    func deleteWorkflowPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `WorkflowsClient.updateWorkflow`.
    func updateWorkflowPollingUntilDone(request: UpdateWorkflowRequest) async throws
      -> any GoogleGax.PollableOperation<Workflow>

    /// See `WorkflowsClient.updateWorkflow`.
    func updateWorkflowPollingUntilDone(
      workflow: Workflow?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<Workflow>

    /// See `WorkflowsClient.listWorkflows`.
    func listWorkflows(
      request: ListWorkflowsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowsResponse

    /// See `WorkflowsClient.getWorkflow`.
    func getWorkflow(
      request: GetWorkflowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsV1.Workflow

    /// See `WorkflowsClient.createWorkflow`.
    func createWorkflow(
      request: CreateWorkflowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkflowsClient.createWorkflow`.
    func createWorkflowPollingUntilDone(
      request: CreateWorkflowRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Workflow>

    /// See `WorkflowsClient.deleteWorkflow`.
    func deleteWorkflow(
      request: DeleteWorkflowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkflowsClient.deleteWorkflow`.
    func deleteWorkflowPollingUntilDone(
      request: DeleteWorkflowRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `WorkflowsClient.updateWorkflow`.
    func updateWorkflow(
      request: UpdateWorkflowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkflowsClient.updateWorkflow`.
    func updateWorkflowPollingUntilDone(
      request: UpdateWorkflowRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Workflow>

    /// See `WorkflowsClient.listWorkflowRevisions`.
    func listWorkflowRevisions(
      request: ListWorkflowRevisionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse

    /// See `WorkflowsClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `WorkflowsClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `WorkflowsClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `WorkflowsClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.WorkflowsProtocol {
  public func listWorkflows(request: ListWorkflowsRequest) async throws
    -> GoogleCloudWorkflowsV1.ListWorkflowsResponse
  {
    try await self.listWorkflows(request: request, options: .init())
  }

  public func listWorkflows(
    request: ListWorkflowsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listWorkflowsByItems(
    request: ListWorkflowsRequest
  ) -> any AsyncSequence<Workflow, Swift.Error> & Sendable {
    self.listWorkflowsByItems(request: request, options: .init())
  }

  /// Lists workflows in a given project and location.
  /// The default order is not specified.
  ///
  /// @Snippet(path: "Workflows_ListWorkflows")
  public func listWorkflowsByItems(
    request: ListWorkflowsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Workflow, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudWorkflowsV1.ListWorkflowsResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listWorkflows(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listWorkflowsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Workflow, Swift.Error> & Sendable {
    let request = ListWorkflowsRequest().with {
      $0.parent = parent
    }
    return self.listWorkflowsByItems(request: request)
  }

  public func getWorkflow(request: GetWorkflowRequest) async throws
    -> GoogleCloudWorkflowsV1.Workflow
  {
    try await self.getWorkflow(request: request, options: .init())
  }

  public func getWorkflow(
    request: GetWorkflowRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkflowsV1.Workflow {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getWorkflow(
    name: Swift.String,
  ) async throws -> GoogleCloudWorkflowsV1.Workflow {
    let request = GetWorkflowRequest().with {
      $0.name = name
    }
    return try await self.getWorkflow(request: request)
  }

  public func createWorkflow(request: CreateWorkflowRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createWorkflow(request: request, options: .init())
  }

  public func createWorkflow(
    request: CreateWorkflowRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createWorkflowPollingUntilDone(request: CreateWorkflowRequest) async throws
    -> any GoogleGax.PollableOperation<Workflow>
  {
    try await self.createWorkflowPollingUntilDone(request: request, options: .init())
  }

  public func createWorkflowPollingUntilDone(
    request: CreateWorkflowRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Workflow> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Workflow>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createWorkflowPollingUntilDone(
    parent: Swift.String,
    workflow: Workflow?,
    workflowId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Workflow> {
    let request = CreateWorkflowRequest().with {
      $0.parent = parent
      $0.workflow = workflow
      $0.workflowId = workflowId
    }
    return try await self.createWorkflowPollingUntilDone(request: request)
  }

  public func deleteWorkflow(request: DeleteWorkflowRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteWorkflow(request: request, options: .init())
  }

  public func deleteWorkflow(
    request: DeleteWorkflowRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteWorkflowPollingUntilDone(request: DeleteWorkflowRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteWorkflowPollingUntilDone(request: request, options: .init())
  }

  public func deleteWorkflowPollingUntilDone(
    request: DeleteWorkflowRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteWorkflowPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteWorkflowRequest().with {
      $0.name = name
    }
    return try await self.deleteWorkflowPollingUntilDone(request: request)
  }

  public func updateWorkflow(request: UpdateWorkflowRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateWorkflow(request: request, options: .init())
  }

  public func updateWorkflow(
    request: UpdateWorkflowRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateWorkflowPollingUntilDone(request: UpdateWorkflowRequest) async throws
    -> any GoogleGax.PollableOperation<Workflow>
  {
    try await self.updateWorkflowPollingUntilDone(request: request, options: .init())
  }

  public func updateWorkflowPollingUntilDone(
    request: UpdateWorkflowRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Workflow> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Workflow>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateWorkflowPollingUntilDone(
    workflow: Workflow?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Workflow> {
    let request = UpdateWorkflowRequest().with {
      $0.workflow = workflow
      $0.updateMask = updateMask
    }
    return try await self.updateWorkflowPollingUntilDone(request: request)
  }

  public func listWorkflowRevisions(request: ListWorkflowRevisionsRequest) async throws
    -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse
  {
    try await self.listWorkflowRevisions(request: request, options: .init())
  }

  public func listWorkflowRevisions(
    request: ListWorkflowRevisionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listWorkflowRevisionsByItems(
    request: ListWorkflowRevisionsRequest
  ) -> any AsyncSequence<Workflow, Swift.Error> & Sendable {
    self.listWorkflowRevisionsByItems(request: request, options: .init())
  }

  /// Lists revisions for a given workflow.
  ///
  /// @Snippet(path: "Workflows_ListWorkflowRevisions")
  public func listWorkflowRevisionsByItems(
    request: ListWorkflowRevisionsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Workflow, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse in
      var request = request
      request.pageToken = token
      return try await self.listWorkflowRevisions(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Workflows_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Workflows_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }
}
