// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import Logging

/// Workflows is used to deploy and execute workflow programs.
/// Workflows makes sure the program executes reliably, despite hardware and
/// networking interruptions.
///
/// @Snippet(path: "WorkflowsQuickstart")
public protocol Workflows {
  /// Lists workflows in a given project and location.
  /// The default order is not specified.
  ///
  /// @Snippet(path: "Workflows_ListWorkflows")
  func listWorkflows(request: ListWorkflowsRequest) async throws
    -> GoogleCloudWorkflowsV1.ListWorkflowsResponse

  /// Lists workflows in a given project and location.
  /// The default order is not specified.
  func listWorkflows(
    byItem: ListWorkflowsRequest
  ) throws -> any AsyncSequence<Workflow, Swift.Error>

  /// Gets details of a single workflow.
  ///
  /// @Snippet(path: "Workflows_GetWorkflow")
  func getWorkflow(request: GetWorkflowRequest) async throws -> GoogleCloudWorkflowsV1.Workflow

  /// Creates a new workflow. If a workflow with the specified name already
  /// exists in the specified project and location, the long running operation
  /// returns a [ALREADY_EXISTS][google.rpc.Code.ALREADY_EXISTS] error.
  ///
  /// @Snippet(path: "Workflows_CreateWorkflow")
  func createWorkflow(request: CreateWorkflowRequest) async throws -> GoogleLongrunning.Operation

  /// Creates a new workflow. If a workflow with the specified name already
  /// exists in the specified project and location, the long running operation
  /// returns a [ALREADY_EXISTS][google.rpc.Code.ALREADY_EXISTS] error.
  func createWorkflow(withPolling: CreateWorkflowRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Workflow>

  /// Deletes a workflow with the specified name.
  /// This method also cancels and deletes all running executions of the
  /// workflow.
  ///
  /// @Snippet(path: "Workflows_DeleteWorkflow")
  func deleteWorkflow(request: DeleteWorkflowRequest) async throws -> GoogleLongrunning.Operation

  /// Deletes a workflow with the specified name.
  /// This method also cancels and deletes all running executions of the
  /// workflow.
  func deleteWorkflow(withPolling: DeleteWorkflowRequest) async throws -> any GoogleCloudGax
    .PollableOperation<GoogleCloudWkt.Empty>

  /// Updates an existing workflow.
  /// Running this method has no impact on already running executions of the
  /// workflow. A new revision of the workflow might be created as a result of a
  /// successful update operation. In that case, the new revision is used
  /// in new workflow executions.
  ///
  /// @Snippet(path: "Workflows_UpdateWorkflow")
  func updateWorkflow(request: UpdateWorkflowRequest) async throws -> GoogleLongrunning.Operation

  /// Updates an existing workflow.
  /// Running this method has no impact on already running executions of the
  /// workflow. A new revision of the workflow might be created as a result of a
  /// successful update operation. In that case, the new revision is used
  /// in new workflow executions.
  func updateWorkflow(withPolling: UpdateWorkflowRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Workflow>

  /// Lists revisions for a given workflow.
  ///
  /// @Snippet(path: "Workflows_ListWorkflowRevisions")
  func listWorkflowRevisions(request: ListWorkflowRevisionsRequest) async throws
    -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse

  /// Lists revisions for a given workflow.
  func listWorkflowRevisions(
    byItem: ListWorkflowRevisionsRequest
  ) throws -> any AsyncSequence<Workflow, Swift.Error>

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Workflows_ListLocations")
  func listLocations(request: ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse

  /// Lists information about the supported locations for this service.
  func listLocations(
    byItem: ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

  /// Gets information about a location.
  ///
  /// @Snippet(path: "Workflows_GetLocation")
  func getLocation(request: GetLocationRequest) async throws -> GoogleCloudLocation.Location

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Workflows_ListOperations")
  func listOperations(request: ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func listOperations(
    byItem: ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Workflows_GetOperation")
  func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Workflows_DeleteOperation")
  func deleteOperation(request: DeleteOperationRequest) async throws

  /// Lists workflows in a given project and location.
  /// The default order is not specified.
  ///
  /// @Snippet(path: "Workflows_ListWorkflows")
  func listWorkflows(
    request: ListWorkflowsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowsResponse

  /// Lists workflows in a given project and location.
  /// The default order is not specified.
  func listWorkflows(
    byItem: ListWorkflowsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Workflow, Swift.Error>

  /// Gets details of a single workflow.
  ///
  /// @Snippet(path: "Workflows_GetWorkflow")
  func getWorkflow(
    request: GetWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkflowsV1.Workflow

  /// Creates a new workflow. If a workflow with the specified name already
  /// exists in the specified project and location, the long running operation
  /// returns a [ALREADY_EXISTS][google.rpc.Code.ALREADY_EXISTS] error.
  ///
  /// @Snippet(path: "Workflows_CreateWorkflow")
  func createWorkflow(
    request: CreateWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Creates a new workflow. If a workflow with the specified name already
  /// exists in the specified project and location, the long running operation
  /// returns a [ALREADY_EXISTS][google.rpc.Code.ALREADY_EXISTS] error.
  func createWorkflow(
    withPolling: CreateWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Workflow>

  /// Deletes a workflow with the specified name.
  /// This method also cancels and deletes all running executions of the
  /// workflow.
  ///
  /// @Snippet(path: "Workflows_DeleteWorkflow")
  func deleteWorkflow(
    request: DeleteWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Deletes a workflow with the specified name.
  /// This method also cancels and deletes all running executions of the
  /// workflow.
  func deleteWorkflow(
    withPolling: DeleteWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<GoogleCloudWkt.Empty>

  /// Updates an existing workflow.
  /// Running this method has no impact on already running executions of the
  /// workflow. A new revision of the workflow might be created as a result of a
  /// successful update operation. In that case, the new revision is used
  /// in new workflow executions.
  ///
  /// @Snippet(path: "Workflows_UpdateWorkflow")
  func updateWorkflow(
    request: UpdateWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Updates an existing workflow.
  /// Running this method has no impact on already running executions of the
  /// workflow. A new revision of the workflow might be created as a result of a
  /// successful update operation. In that case, the new revision is used
  /// in new workflow executions.
  func updateWorkflow(
    withPolling: UpdateWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Workflow>

  /// Lists revisions for a given workflow.
  ///
  /// @Snippet(path: "Workflows_ListWorkflowRevisions")
  func listWorkflowRevisions(
    request: ListWorkflowRevisionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse

  /// Lists revisions for a given workflow.
  func listWorkflowRevisions(
    byItem: ListWorkflowRevisionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Workflow, Swift.Error>

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Workflows_ListLocations")
  func listLocations(
    request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse

  /// Lists information about the supported locations for this service.
  func listLocations(
    byItem: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

  /// Gets information about a location.
  ///
  /// @Snippet(path: "Workflows_GetLocation")
  func getLocation(
    request: GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Workflows_ListOperations")
  func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Workflows_GetOperation")
  func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Workflows_DeleteOperation")
  func deleteOperation(
    request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws
}

extension Clients {
  /// The recommended implementation for ``Workflows``.
  public class WorkflowsClient: Workflows {
    let inner: any WorkflowsStub

    /// Creates a new `WorkflowsClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any WorkflowsStub = try WorkflowsTransport(options)
      inner = WorkflowsRetry(inner, options: options)
      if let logger = options.logger {
        inner = WorkflowsLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// See `Workflows.listWorkflows`
    public func listWorkflows(
      request: ListWorkflowsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowsResponse {
      try await self.inner.listWorkflows(request: request, options: options)
    }

    /// Lists workflows in a given project and location.
    /// The default order is not specified.
    public func listWorkflows(
      byItem: ListWorkflowsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Workflow, Swift.Error> {
      let listRpc = {
        (token: String) async throws -> GoogleCloudWorkflowsV1.ListWorkflowsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listWorkflows(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `Workflows.getWorkflow`
    public func getWorkflow(
      request: GetWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsV1.Workflow {
      try await self.inner.getWorkflow(request: request, options: options)
    }

    /// See `Workflows.createWorkflow`
    public func createWorkflow(
      request: CreateWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.createWorkflow(request: request, options: options)
    }

    /// Creates a new workflow. If a workflow with the specified name already
    /// exists in the specified project and location, the long running operation
    /// returns a [ALREADY_EXISTS][google.rpc.Code.ALREADY_EXISTS] error.
    public func createWorkflow(
      withPolling: CreateWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Workflow> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<Workflow>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try Workflow(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.createWorkflow(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Workflow>.State in
        let op = try await self.getOperation(request: .init(name: rawOp.name), options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `Workflows.deleteWorkflow`
    public func deleteWorkflow(
      request: DeleteWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.deleteWorkflow(request: request, options: options)
    }

    /// Deletes a workflow with the specified name.
    /// This method also cancels and deletes all running executions of the
    /// workflow.
    public func deleteWorkflow(
      withPolling: DeleteWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<GoogleCloudWkt.Empty> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<GoogleCloudWkt.Empty>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try GoogleCloudWkt.Empty(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.deleteWorkflow(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        () async throws -> GoogleCloudGax._PollableOperationImpl<GoogleCloudWkt.Empty>.State in
        let op = try await self.getOperation(request: .init(name: rawOp.name), options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `Workflows.updateWorkflow`
    public func updateWorkflow(
      request: UpdateWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.updateWorkflow(request: request, options: options)
    }

    /// Updates an existing workflow.
    /// Running this method has no impact on already running executions of the
    /// workflow. A new revision of the workflow might be created as a result of a
    /// successful update operation. In that case, the new revision is used
    /// in new workflow executions.
    public func updateWorkflow(
      withPolling: UpdateWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Workflow> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<Workflow>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try Workflow(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.updateWorkflow(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Workflow>.State in
        let op = try await self.getOperation(request: .init(name: rawOp.name), options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `Workflows.listWorkflowRevisions`
    public func listWorkflowRevisions(
      request: ListWorkflowRevisionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse {
      try await self.inner.listWorkflowRevisions(request: request, options: options)
    }

    /// Lists revisions for a given workflow.
    public func listWorkflowRevisions(
      byItem: ListWorkflowRevisionsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Workflow, Swift.Error> {
      let listRpc = {
        (token: String) async throws -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listWorkflowRevisions(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `Workflows.listLocations`
    public func listLocations(
      request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self.inner.listLocations(request: request, options: options)
    }

    /// Lists information about the supported locations for this service.
    public func listLocations(
      byItem: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
      let listRpc = { (token: String) async throws -> GoogleCloudLocation.ListLocationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listLocations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `Workflows.getLocation`
    public func getLocation(
      request: GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self.inner.getLocation(request: request, options: options)
    }

    /// See `Workflows.listOperations`
    public func listOperations(
      request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
    public func listOperations(
      byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
      let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `Workflows.getOperation`
    public func getOperation(
      request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// See `Workflows.deleteOperation`
    public func deleteOperation(
      request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.deleteOperation(request: request, options: options)
    }
  }
}

// Default implementations
extension Workflows {
  public func listWorkflows(request: ListWorkflowsRequest) async throws
    -> GoogleCloudWorkflowsV1.ListWorkflowsResponse
  {
    try await self.listWorkflows(request: request, options: .init())
  }

  public func listWorkflows(
    request: ListWorkflowsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listWorkflows(
    byItem: ListWorkflowsRequest
  ) throws -> any AsyncSequence<Workflow, Swift.Error> {
    try self.listWorkflows(byItem: byItem, options: .init())
  }

  public func listWorkflows(
    byItem: ListWorkflowsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Workflow, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleCloudWorkflowsV1.ListWorkflowsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getWorkflow(request: GetWorkflowRequest) async throws
    -> GoogleCloudWorkflowsV1.Workflow
  {
    try await self.getWorkflow(request: request, options: .init())
  }

  public func getWorkflow(
    request: GetWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkflowsV1.Workflow {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createWorkflow(request: CreateWorkflowRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.createWorkflow(request: request, options: .init())
  }

  public func createWorkflow(
    request: CreateWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createWorkflow(withPolling: CreateWorkflowRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Workflow>
  {
    try await self.createWorkflow(withPolling: withPolling, options: .init())
  }

  public func createWorkflow(
    withPolling: CreateWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Workflow> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Workflow>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteWorkflow(request: DeleteWorkflowRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.deleteWorkflow(request: request, options: .init())
  }

  public func deleteWorkflow(
    request: DeleteWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteWorkflow(withPolling: DeleteWorkflowRequest) async throws -> any GoogleCloudGax
    .PollableOperation<GoogleCloudWkt.Empty>
  {
    try await self.deleteWorkflow(withPolling: withPolling, options: .init())
  }

  public func deleteWorkflow(
    withPolling: DeleteWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<GoogleCloudWkt.Empty> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<GoogleCloudWkt.Empty>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateWorkflow(request: UpdateWorkflowRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.updateWorkflow(request: request, options: .init())
  }

  public func updateWorkflow(
    request: UpdateWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateWorkflow(withPolling: UpdateWorkflowRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Workflow>
  {
    try await self.updateWorkflow(withPolling: withPolling, options: .init())
  }

  public func updateWorkflow(
    withPolling: UpdateWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Workflow> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Workflow>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func listWorkflowRevisions(request: ListWorkflowRevisionsRequest) async throws
    -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse
  {
    try await self.listWorkflowRevisions(request: request, options: .init())
  }

  public func listWorkflowRevisions(
    request: ListWorkflowRevisionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listWorkflowRevisions(
    byItem: ListWorkflowRevisionsRequest
  ) throws -> any AsyncSequence<Workflow, Swift.Error> {
    try self.listWorkflowRevisions(byItem: byItem, options: .init())
  }

  public func listWorkflowRevisions(
    byItem: ListWorkflowRevisionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Workflow, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listLocations(request: ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GetLocationRequest) async throws -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(request: DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
