// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import GoogleCloudGax

/// Workflows is used to deploy and execute workflow programs.
/// Workflows makes sure the program executes reliably, despite hardware and
/// networking interruptions.
///
/// @Snippet(path: "WorkflowsQuickstart")
public class WorkflowsClient: Clients.WorkflowsProtocol {
  let inner: any Clients.WorkflowsStub

  /// Creates a new `WorkflowsClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.WorkflowsStub = try Clients.WorkflowsTransport(options)
    inner = Clients.WorkflowsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.WorkflowsLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists workflows in a given project and location.
  /// The default order is not specified.
  ///
  /// @Snippet(path: "Workflows_ListWorkflows")
  public func listWorkflows(
    request: ListWorkflowsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowsResponse {
    try await self.inner.listWorkflows(request: request, options: options)
  }

  /// Lists workflows in a given project and location.
  /// The default order is not specified.
  ///
  /// @Snippet(path: "Workflows_ListWorkflows")
  public func listWorkflows(
    byItem: ListWorkflowsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Workflow, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleCloudWorkflowsV1.ListWorkflowsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listWorkflows(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single workflow.
  ///
  /// @Snippet(path: "Workflows_GetWorkflow")
  public func getWorkflow(
    request: GetWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkflowsV1.Workflow {
    try await self.inner.getWorkflow(request: request, options: options)
  }

  /// Creates a new workflow. If a workflow with the specified name already
  /// exists in the specified project and location, the long running operation
  /// returns a [ALREADY_EXISTS][google.rpc.Code.ALREADY_EXISTS] error.
  ///
  /// @Snippet(path: "Workflows_CreateWorkflow")
  public func createWorkflow(
    request: CreateWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.createWorkflow(request: request, options: options)
  }

  /// Creates a new workflow. If a workflow with the specified name already
  /// exists in the specified project and location, the long running operation
  /// returns a [ALREADY_EXISTS][google.rpc.Code.ALREADY_EXISTS] error.
  ///
  /// @Snippet(path: "Workflows_CreateWorkflow")
  public func createWorkflow(
    withPolling: CreateWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Workflow> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Workflow>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Workflow(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createWorkflow(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Workflow>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Deletes a workflow with the specified name.
  /// This method also cancels and deletes all running executions of the
  /// workflow.
  ///
  /// @Snippet(path: "Workflows_DeleteWorkflow")
  public func deleteWorkflow(
    request: DeleteWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.deleteWorkflow(request: request, options: options)
  }

  /// Deletes a workflow with the specified name.
  /// This method also cancels and deletes all running executions of the
  /// workflow.
  ///
  /// @Snippet(path: "Workflows_DeleteWorkflow")
  public func deleteWorkflow(
    withPolling: DeleteWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteWorkflow(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Updates an existing workflow.
  /// Running this method has no impact on already running executions of the
  /// workflow. A new revision of the workflow might be created as a result of a
  /// successful update operation. In that case, the new revision is used
  /// in new workflow executions.
  ///
  /// @Snippet(path: "Workflows_UpdateWorkflow")
  public func updateWorkflow(
    request: UpdateWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.updateWorkflow(request: request, options: options)
  }

  /// Updates an existing workflow.
  /// Running this method has no impact on already running executions of the
  /// workflow. A new revision of the workflow might be created as a result of a
  /// successful update operation. In that case, the new revision is used
  /// in new workflow executions.
  ///
  /// @Snippet(path: "Workflows_UpdateWorkflow")
  public func updateWorkflow(
    withPolling: UpdateWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Workflow> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Workflow>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Workflow(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateWorkflow(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Workflow>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Lists revisions for a given workflow.
  ///
  /// @Snippet(path: "Workflows_ListWorkflowRevisions")
  public func listWorkflowRevisions(
    request: ListWorkflowRevisionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse {
    try await self.inner.listWorkflowRevisions(request: request, options: options)
  }

  /// Lists revisions for a given workflow.
  ///
  /// @Snippet(path: "Workflows_ListWorkflowRevisions")
  public func listWorkflowRevisions(
    byItem: ListWorkflowRevisionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Workflow, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listWorkflowRevisions(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Workflows_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Workflows_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "Workflows_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Workflows_ListOperations")
  public func listOperations(
    request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Workflows_ListOperations")
  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Workflows_GetOperation")
  func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Workflows_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `WorkflowsClient`.
  ///
  /// To mock `WorkflowsClient` change your functions to receive
  /// `some WorkflowsProtocol` or `any WorkflowsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol WorkflowsProtocol {
    /// See `WorkflowsClient.listWorkflows`.
    func listWorkflows(request: ListWorkflowsRequest) async throws
      -> GoogleCloudWorkflowsV1.ListWorkflowsResponse

    /// See `WorkflowsClient.listWorkflows`.
    func listWorkflows(
      byItem: ListWorkflowsRequest
    ) throws -> any AsyncSequence<Workflow, Swift.Error>

    /// See `WorkflowsClient.listWorkflows`.
    func listWorkflows(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Workflow, Swift.Error>

    /// See `WorkflowsClient.getWorkflow`.
    func getWorkflow(request: GetWorkflowRequest) async throws -> GoogleCloudWorkflowsV1.Workflow

    /// See `WorkflowsClient.getWorkflow`.
    func getWorkflow(
      name: Swift.String,
    ) async throws -> GoogleCloudWorkflowsV1.Workflow

    /// See `WorkflowsClient.createWorkflow`.
    func createWorkflow(request: CreateWorkflowRequest) async throws -> GoogleLongrunning.Operation

    /// See `WorkflowsClient.createWorkflow`.
    func createWorkflow(withPolling: CreateWorkflowRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Workflow>

    /// See `WorkflowsClient.createWorkflow`.
    func createWorkflow(
      parent: Swift.String,
      workflow: Workflow?,
      workflowId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Workflow>

    /// See `WorkflowsClient.deleteWorkflow`.
    func deleteWorkflow(request: DeleteWorkflowRequest) async throws -> GoogleLongrunning.Operation

    /// See `WorkflowsClient.deleteWorkflow`.
    func deleteWorkflow(withPolling: DeleteWorkflowRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `WorkflowsClient.deleteWorkflow`.
    func deleteWorkflow(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `WorkflowsClient.updateWorkflow`.
    func updateWorkflow(request: UpdateWorkflowRequest) async throws -> GoogleLongrunning.Operation

    /// See `WorkflowsClient.updateWorkflow`.
    func updateWorkflow(withPolling: UpdateWorkflowRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Workflow>

    /// See `WorkflowsClient.updateWorkflow`.
    func updateWorkflow(
      workflow: Workflow?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Workflow>

    /// See `WorkflowsClient.listWorkflowRevisions`.
    func listWorkflowRevisions(request: ListWorkflowRevisionsRequest) async throws
      -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse

    /// See `WorkflowsClient.listWorkflowRevisions`.
    func listWorkflowRevisions(
      byItem: ListWorkflowRevisionsRequest
    ) throws -> any AsyncSequence<Workflow, Swift.Error>

    /// See `WorkflowsClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `WorkflowsClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `WorkflowsClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `WorkflowsClient.listOperations`.
    func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
      -> GoogleLongrunning.ListOperationsResponse

    /// See `WorkflowsClient.listOperations`.
    func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `WorkflowsClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `WorkflowsClient.deleteOperation`.
    func deleteOperation(request: GoogleLongrunning.DeleteOperationRequest) async throws

    /// See `WorkflowsClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `WorkflowsClient.listWorkflows`.
    func listWorkflows(
      request: ListWorkflowsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowsResponse

    /// See `WorkflowsClient.listWorkflows`.
    func listWorkflows(
      byItem: ListWorkflowsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Workflow, Swift.Error>

    /// See `WorkflowsClient.getWorkflow`.
    func getWorkflow(
      request: GetWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsV1.Workflow

    /// See `WorkflowsClient.createWorkflow`.
    func createWorkflow(
      request: CreateWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `WorkflowsClient.createWorkflow`.
    func createWorkflow(
      withPolling: CreateWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Workflow>

    /// See `WorkflowsClient.deleteWorkflow`.
    func deleteWorkflow(
      request: DeleteWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `WorkflowsClient.deleteWorkflow`.
    func deleteWorkflow(
      withPolling: DeleteWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `WorkflowsClient.updateWorkflow`.
    func updateWorkflow(
      request: UpdateWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `WorkflowsClient.updateWorkflow`.
    func updateWorkflow(
      withPolling: UpdateWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Workflow>

    /// See `WorkflowsClient.listWorkflowRevisions`.
    func listWorkflowRevisions(
      request: ListWorkflowRevisionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse

    /// See `WorkflowsClient.listWorkflowRevisions`.
    func listWorkflowRevisions(
      byItem: ListWorkflowRevisionsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Workflow, Swift.Error>

    /// See `WorkflowsClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `WorkflowsClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `WorkflowsClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `WorkflowsClient.listOperations`.
    func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse

    /// See `WorkflowsClient.listOperations`.
    func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `WorkflowsClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.WorkflowsProtocol {
  public func listWorkflows(request: ListWorkflowsRequest) async throws
    -> GoogleCloudWorkflowsV1.ListWorkflowsResponse
  {
    try await self.listWorkflows(request: request, options: .init())
  }

  public func listWorkflows(
    request: ListWorkflowsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listWorkflows(
    byItem: ListWorkflowsRequest
  ) throws -> any AsyncSequence<Workflow, Swift.Error> {
    try self.listWorkflows(byItem: byItem, options: .init())
  }

  public func listWorkflows(
    byItem: ListWorkflowsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Workflow, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleCloudWorkflowsV1.ListWorkflowsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listWorkflows(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Workflow, Swift.Error> {
    let request = ListWorkflowsRequest().with {
      $0.parent = parent
    }
    return try self.listWorkflows(byItem: request)
  }

  public func getWorkflow(request: GetWorkflowRequest) async throws
    -> GoogleCloudWorkflowsV1.Workflow
  {
    try await self.getWorkflow(request: request, options: .init())
  }

  public func getWorkflow(
    request: GetWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkflowsV1.Workflow {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getWorkflow(
    name: Swift.String,
  ) async throws -> GoogleCloudWorkflowsV1.Workflow {
    let request = GetWorkflowRequest().with {
      $0.name = name
    }
    return try await self.getWorkflow(request: request)
  }

  public func createWorkflow(request: CreateWorkflowRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.createWorkflow(request: request, options: .init())
  }

  public func createWorkflow(
    request: CreateWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createWorkflow(withPolling: CreateWorkflowRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Workflow>
  {
    try await self.createWorkflow(withPolling: withPolling, options: .init())
  }

  public func createWorkflow(
    withPolling: CreateWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Workflow> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Workflow>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createWorkflow(
    parent: Swift.String,
    workflow: Workflow?,
    workflowId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Workflow> {
    let request = CreateWorkflowRequest().with {
      $0.parent = parent
      $0.workflow = workflow
      $0.workflowId = workflowId
    }
    return try await self.createWorkflow(withPolling: request)
  }

  public func deleteWorkflow(request: DeleteWorkflowRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.deleteWorkflow(request: request, options: .init())
  }

  public func deleteWorkflow(
    request: DeleteWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteWorkflow(withPolling: DeleteWorkflowRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.deleteWorkflow(withPolling: withPolling, options: .init())
  }

  public func deleteWorkflow(
    withPolling: DeleteWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteWorkflow(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteWorkflowRequest().with {
      $0.name = name
    }
    return try await self.deleteWorkflow(withPolling: request)
  }

  public func updateWorkflow(request: UpdateWorkflowRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.updateWorkflow(request: request, options: .init())
  }

  public func updateWorkflow(
    request: UpdateWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateWorkflow(withPolling: UpdateWorkflowRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Workflow>
  {
    try await self.updateWorkflow(withPolling: withPolling, options: .init())
  }

  public func updateWorkflow(
    withPolling: UpdateWorkflowRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Workflow> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Workflow>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateWorkflow(
    workflow: Workflow?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Workflow> {
    let request = UpdateWorkflowRequest().with {
      $0.workflow = workflow
      $0.updateMask = updateMask
    }
    return try await self.updateWorkflow(withPolling: request)
  }

  public func listWorkflowRevisions(request: ListWorkflowRevisionsRequest) async throws
    -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse
  {
    try await self.listWorkflowRevisions(request: request, options: .init())
  }

  public func listWorkflowRevisions(
    request: ListWorkflowRevisionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listWorkflowRevisions(
    byItem: ListWorkflowRevisionsRequest
  ) throws -> any AsyncSequence<Workflow, Swift.Error> {
    try self.listWorkflowRevisions(byItem: byItem, options: .init())
  }

  public func listWorkflowRevisions(
    byItem: ListWorkflowRevisionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Workflow, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let request = GoogleLongrunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongrunning.GetOperationRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongrunning.Operation {
    let request = GoogleLongrunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongrunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongrunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }
}
