// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import Logging

extension Clients {
  protocol WorkflowsStub {
    func listWorkflows(
      request: ListWorkflowsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowsResponse

    func getWorkflow(
      request: GetWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsV1.Workflow

    func createWorkflow(
      request: CreateWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    func deleteWorkflow(
      request: DeleteWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    func updateWorkflow(
      request: UpdateWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    func listWorkflowRevisions(
      request: ListWorkflowRevisionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse

    func listLocations(
      request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse

    func getOperation(
      request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    func deleteOperation(
      request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }

  class WorkflowsTransport: WorkflowsStub {
    let inner: GoogleCloudGax.HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax.HTTPClient(
        from: options, withDefaultEndpoint: "https://workflows.googleapis.com")
    }

    public func listWorkflows(
      request: ListWorkflowsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/workflows"
      }()
      var query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.orderBy, prefix: "orderBy"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudWorkflowsV1.ListWorkflowsResponse.self, from: data)
    }

    public func getWorkflow(
      request: GetWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsV1.Workflow {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.revisionId, prefix: "revisionId"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudWorkflowsV1.Workflow.self, from: data)
    }

    public func createWorkflow(
      request: CreateWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/workflows"
      }()
      var query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.workflowId, prefix: "workflowId"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      if let body = request.workflow {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleLongrunning.Operation.self, from: data)
    }

    public func deleteWorkflow(
      request: DeleteWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "DELETE"
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleLongrunning.Operation.self, from: data)
    }

    public func updateWorkflow(
      request: UpdateWorkflowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.workflow.map({ $0.name }), !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.workflow.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "PATCH"
      if let body = request.workflow {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleLongrunning.Operation.self, from: data)
    }

    public func listWorkflowRevisions(
      request: ListWorkflowRevisionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0):listRevisions"
      }()
      var query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudWorkflowsV1.ListWorkflowRevisionsResponse.self, from: data)
    }

    public func listLocations(
      request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/locations"
      }()
      var query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudLocation.ListLocationsResponse.self, from: data)
    }

    public func getLocation(
      request: GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudLocation.Location.self, from: data)
    }

    public func listOperations(
      request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/operations"
      }()
      var query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(
        contentsOf: try encoder.encode(request.returnPartialSuccess, prefix: "returnPartialSuccess")
      )
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleLongrunning.ListOperationsResponse.self, from: data)
    }

    public func getOperation(
      request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleLongrunning.Operation.self, from: data)
    }

    public func deleteOperation(
      request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "DELETE"
      _ = try await self.inner.rpc(for: req).get()
    }
  }
}
